export default {
    "GENERIC_TYPE_APPLIANCE": {
        "SPECIFIC_TYPE_NOT_USED":                         0x00,
        "SPECIFIC_TYPE_GENERAL_APPLIANCE":                0x01,
        "SPECIFIC_TYPE_KITCHEN_APPLIANCE":                0x02,
        "SPECIFIC_TYPE_LAUNDRY_APPLIANCE":                0x03,
    },
    "GENERIC_TYPE_AV_CONTROL_POINT": {
        "SPECIFIC_TYPE_NOT_USED":                         0x00,
        "SPECIFIC_TYPE_SOUND_SWITCH":                     0x01,
        "SPECIFIC_TYPE_SATELLITE_RECEIVER":               0x04,
        "SPECIFIC_TYPE_SATELLITE_RECEIVER_V2":            0x11,
        "SPECIFIC_TYPE_DOORBELL":                         0x12,
    },
    "GENERIC_TYPE_DISPLAY": {
        "SPECIFIC_TYPE_NOT_USED":                         0x00,
        "SPECIFIC_TYPE_SIMPLE_DISPLAY":                   0x01,
    },
    "GENERIC_TYPE_ENTRY_CONTROL": {
        "SPECIFIC_TYPE_NOT_USED":                         0x00,
        "SPECIFIC_TYPE_DOOR_LOCK":                        0x01,
        "SPECIFIC_TYPE_ADVANCED_DOOR_LOCK":               0x02,
        "SPECIFIC_TYPE_SECURE_KEYPAD_DOOR_LOCK":          0x03,
        "SPECIFIC_TYPE_SECURE_KEYPAD_DOOR_LOCK_DEADBOLT": 0x04,
        "SPECIFIC_TYPE_SECURE_DOOR":                      0x05,
        "SPECIFIC_TYPE_SECURE_GATE":                      0x06,
        "SPECIFIC_TYPE_SECURE_BARRIER_ADDON":             0x07,
        "SPECIFIC_TYPE_SECURE_BARRIER_OPEN_ONLY":         0x08,
        "SPECIFIC_TYPE_SECURE_BARRIER_CLOSE_ONLY":        0x09,
        "SPECIFIC_TYPE_SECURE_LOCKBOX":                   0x0A,
        "SPECIFIC_TYPE_SECURE_KEYPAD":                    0x0B,
    },
    "GENERIC_TYPE_GENERIC_CONTROLLER": {
        "SPECIFIC_TYPE_NOT_USED":                         0x00,
        "SPECIFIC_TYPE_PORTABLE_REMOTE_CONTROLLER":       0x01,
        "SPECIFIC_TYPE_PORTABLE_SCENE_CONTROLLER":        0x02,
        "SPECIFIC_TYPE_PORTABLE_INSTALLER_TOOL":          0x03,
        "SPECIFIC_TYPE_REMOTE_CONTROL_AV":                0x04,
        "SPECIFIC_TYPE_REMOTE_CONTROL_SIMPLE":            0x06,
    },
    "GENERIC_TYPE_METER": {
        "SPECIFIC_TYPE_NOT_USED":                         0x00,
    },
    "GENERIC_TYPE_METER_PULSE": {
        "SPECIFIC_TYPE_NOT_USED":                         0x00,
        "SPECIFIC_TYPE_SIMPLE_METER":                     0x01,
        "SPECIFIC_TYPE_ADV_ENERGY_CONTROL":               0x02,
        "SPECIFIC_TYPE_WHOLE_HOME_METER_SIMPLE":          0x03,
    },
    "GENERIC_TYPE_NETWORK_EXTENDER": {
        "SPECIFIC_TYPE_NOT_USED":                         0x00,
        "SPECIFIC_TYPE_SECURE_EXTENDER":                  0x01,
    },
    "GENERIC_TYPE_NON_INTEROPERABLE": {
        "SPECIFIC_TYPE_NOT_USED":                         0x00,
    },
    "GENERIC_TYPE_REPEATER_SLAVE": {
        "SPECIFIC_TYPE_NOT_USED":                         0x00,
        "SPECIFIC_TYPE_REPEATER_SLAVE":                   0x01,
        "SPECIFIC_TYPE_VIRTUAL_NODE":                     0x02,
    },
    "GENERIC_TYPE_SECURITY_PANEL": {
        "SPECIFIC_TYPE_NOT_USED":                         0x00,
        "SPECIFIC_TYPE_ZONED_SECURITY_PANEL":             0x01,
    },
    "GENERIC_TYPE_SEMI_INTEROPERABLE": {
        "SPECIFIC_TYPE_NOT_USED":                         0x00,
        "SPECIFIC_TYPE_ENERGY_PRODUCTION":                0x01,
    },
    "GENERIC_TYPE_SENSOR_ALARM": {
        "SPECIFIC_TYPE_NOT_USED":                         0x00,
        "SPECIFIC_TYPE_BASIC_ROUTING_ALARM_SENSOR":       0x01,
        "SPECIFIC_TYPE_ROUTING_ALARM_SENSOR":             0x02,
        "SPECIFIC_TYPE_BASIC_ZENSOR_NET_ALARM_SENSOR":    0x03,
        "SPECIFIC_TYPE_ZENSOR_NET_ALARM_SENSOR":          0x04,
        "SPECIFIC_TYPE_ADV_ZENSOR_NET_ALARM_SENSOR":      0x05,
        "SPECIFIC_TYPE_BASIC_ROUTING_SMOKE_SENSOR":       0x06,
        "SPECIFIC_TYPE_ROUTING_SMOKE_SENSOR":             0x07,
        "SPECIFIC_TYPE_BASIC_ZENSOR_NET_SMOKE_SENSOR":    0x08,
        "SPECIFIC_TYPE_ZENSOR_NET_SMOKE_SENSOR":          0x09,
        "SPECIFIC_TYPE_ADV_ZENSOR_NET_SMOKE_SENSOR":      0x0A,
        "SPECIFIC_TYPE_ALARM_SENSOR":                     0x0B,
    },
    "GENERIC_TYPE_SENSOR_BINARY": {
        "SPECIFIC_TYPE_NOT_USED":                         0x00,
        "SPECIFIC_TYPE_ROUTING_SENSOR_BINARY":            0x01,
    },
    "GENERIC_TYPE_SENSOR_MULTILEVEL": {
        "SPECIFIC_TYPE_NOT_USED":                         0x00,
        "SPECIFIC_TYPE_ROUTING_SENSOR_MULTILEVEL":        0x01,
        "SPECIFIC_TYPE_CHIMNEY_FAN":                      0x02,
    },
    "GENERIC_TYPE_SENSOR_NOTIFICATION": {
        "SPECIFIC_TYPE_NOT_USED":                         0x00,
        "SPECIFIC_TYPE_NOTIFICATION_SENSOR":              0x01,
    },
    "GENERIC_TYPE_STATIC_CONTROLLER": {
        "SPECIFIC_TYPE_NOT_USED":                         0x00,
        "SPECIFIC_TYPE_PC_CONTROLLER":                    0x01,
        "SPECIFIC_TYPE_SCENE_CONTROLLER":                 0x02,
        "SPECIFIC_TYPE_STATIC_INSTALLER_TOOL":            0x03,
        "SPECIFIC_TYPE_SET_TOP_BOX":                      0x04,
        "SPECIFIC_TYPE_SUB_SYSTEM_CONTROLLER":            0x05,
        "SPECIFIC_TYPE_TV":                               0x06,
        "SPECIFIC_TYPE_GATEWAY":                          0x07,
    },
    "GENERIC_TYPE_SWITCH_BINARY": {
        "SPECIFIC_TYPE_NOT_USED":                         0x00,
        "SPECIFIC_TYPE_POWER_SWITCH_BINARY":              0x01,
        "SPECIFIC_TYPE_COLOR_TUNABLE_BINARY":             0x02,
        "SPECIFIC_TYPE_SCENE_SWITCH_BINARY":              0x03,
        "SPECIFIC_TYPE_POWER_STRIP":                      0x04,
        "SPECIFIC_TYPE_SIREN":                            0x05,
        "SPECIFIC_TYPE_VALVE_OPEN_CLOSE":                 0x06,
        "SPECIFIC_TYPE_IRRIGATION_CONTROLLER":            0x07,
    },
    "GENERIC_TYPE_SWITCH_MULTILEVEL": {
        "SPECIFIC_TYPE_NOT_USED":                         0x00,
        "SPECIFIC_TYPE_POWER_SWITCH_MULTILEVEL":          0x01,
        "SPECIFIC_TYPE_COLOR_TUNABLE_MULTILEVEL":         0x02,
        "SPECIFIC_TYPE_MOTOR_MULTIPOSITION":              0x03,
        "SPECIFIC_TYPE_SCENE_SWITCH_MULTILEVEL":          0x04,
        "SPECIFIC_TYPE_CLASS_A_MOTOR_CONTROL":            0x05,
        "SPECIFIC_TYPE_CLASS_B_MOTOR_CONTROL":            0x06,
        "SPECIFIC_TYPE_CLASS_C_MOTOR_CONTROL":            0x07,
        "SPECIFIC_TYPE_FAN_SWITCH":                       0x08,
    },
    "GENERIC_TYPE_SWITCH_REMOTE": {
        "SPECIFIC_TYPE_NOT_USED":                         0x00,
        "SPECIFIC_TYPE_SWITCH_REMOTE_BINARY":             0x01,
        "SPECIFIC_TYPE_SWITCH_REMOTE_MULTILEVEL":         0x02,
        "SPECIFIC_TYPE_SWITCH_REMOTE_TOGGLE_BINARY":      0x03,
        "SPECIFIC_TYPE_SWITCH_REMOTE_TOGGLE_MULTILEVEL":  0x04,
    },
    "GENERIC_TYPE_SWITCH_TOGGLE": {
        "SPECIFIC_TYPE_NOT_USED":                         0x00,
        "SPECIFIC_TYPE_SWITCH_TOGGLE_BINARY":             0x01,
        "SPECIFIC_TYPE_SWITCH_TOGGLE_MULTILEVEL":         0x02,
    },
    "GENERIC_TYPE_THERMOSTAT": {
        "SPECIFIC_TYPE_NOT_USED":                         0x00,
        "SPECIFIC_TYPE_THERMOSTAT_HEATING":               0x01,
        "SPECIFIC_TYPE_THERMOSTAT_GENERAL":               0x02,
        "SPECIFIC_TYPE_SETBACK_SCHEDULE_THERMOSTAT":      0x03,
        "SPECIFIC_TYPE_SETPOINT_THERMOSTAT":              0x04,
        "SPECIFIC_TYPE_SETBACK_THERMOSTAT":               0x05,
        "SPECIFIC_TYPE_THERMOSTAT_GENERAL_V2":            0x06,
    },
    "GENERIC_TYPE_VENTILATION": {
        "SPECIFIC_TYPE_NOT_USED":                         0x00,
        "SPECIFIC_TYPE_RESIDENTIAL_HRV":                  0x01,
    },
    "GENERIC_TYPE_WALL_CONTROLLER": {
        "SPECIFIC_TYPE_NOT_USED":                         0x00,
        "SPECIFIC_TYPE_BASIC_WALL_CONTROLLER":            0x01,
    },
    "GENERIC_TYPE_WINDOW_COVERING": {
        "SPECIFIC_TYPE_NOT_USED":                         0x00,
        "SPECIFIC_TYPE_SIMPLE_WINDOW_COVERING":           0x01,
    },
    "GENERIC_TYPE_ZIP_NODE": {
        "SPECIFIC_TYPE_NOT_USED":                         0x00,
        "SPECIFIC_TYPE_ZIP_TUN_NODE":                     0x01,
        "SPECIFIC_TYPE_ZIP_ADV_NODE":                     0x02,
    },
}
