---

#======================================================================================================================#

COMMAND_CLASS_BASIC_1:
  BASIC_SET:
    - 0x20
    - 0x01
    - value

  BASIC_GET:
    - 0x20
    - 0x02

  BASIC_REPORT:
    - 0x20
    - 0x03
    - value

#======================================================================================================================#

COMMAND_CLASS_SWITCH_BINARY_1: &COMMAND_CLASS_SWITCH_BINARY_1
  SWITCH_BINARY_SET:
    - 0x25
    - 0x01
    - value

  SWITCH_BINARY_GET:
    - 0x25
    - 0x02

  SWITCH_BINARY_REPORT:
    - 0x25
    - 0x03
    - value

#----------------------------------------------------------------------------------------------------------------------#

COMMAND_CLASS_SWITCH_BINARY_2:
  <<: *COMMAND_CLASS_SWITCH_BINARY_1

  SWITCH_BINARY_SET:
    - 0x25
    - 0x01
    - value
    - duration

  SWITCH_BINARY_REPORT:
    - 0x25
    - 0x03
    - current_value
    - target_value
    - duration
